### ISSUE TITLE
Multiple SkinnedMesh Detection Not working

### ISSUE THREAD

**Issue by ArieLeo** [nobnak/VertexAnimatorUnity#1]
Hi Nobnak,
I cannot bake multiple skinned mesh animation just like in your video,
it always resulting only one object.
![multiskinnedmesh](https://cloud.githubusercontent.com/assets/6450517/20214758/136817d2-a84b-11e6-9319-c1dee632494d.png)

**Comment by nobnak** [comment]
This functionality is temporary disabled because of the incompatibility between Instancing and Procedural Generated Mesh. Unity team told me that it'll be fixed in Unity 5.5. So I think I'll try to implement this function again on Unity 5.5.

**Comment by ArieLeo** [comment]
ah i see so that's why.

**Comment by nobnak** [comment]
fixed
